//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateNorms
    {
        public int ID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> HoursPerRate { get; set; }
        public string Year { get; set; }
    
        public virtual Positions Positions { get; set; }
    }
}
